### ISSUE TITLE
Invoke javascript?

### ISSUE THREAD

**Issue by mountwebs** [cristianvasquez/obsidian-snippets-plugin#2]
Would it be possible to invoke javascript with this as well? I looked for some way to pass a snippet as a string to node, but couldn't find a way to do it (without creating a file first).

**Comment by steve-bate** [comment]
This code fence configuration worked for me (node v12.16.1, Windows 10).
```json
  "javascript": {
    "template": "node -e \"{{src}}\"",
    "showModal": true,
    "appendOutputContents": true,
    "showRunButtonInPreview": true
  },
```
Example:
````markdown
```javascript
console.log(process.cpuUsage())
```
````
Results in:
````markdown
```output
{ user: 31000, system: 0 }    
```
````

**Comment by cristianvasquez** [comment]
Hello @catword, thank you for the commit. I added javascript to the latest version
